### ISSUE TITLE
我的windows10系统中是没有正常工作的

### ISSUE THREAD

**Issue by anonymou3** [NightDream2016/AutoTypeInputLanguage#1]
系统如下
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19041 暂缺 Build 19041

我在已经预装了英语，同时默认为中文为首选
设置 -> 语言 -> 英语(美国)
[https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values)
我在这上面找到的us的对应的是 
United States - English | 0x00000409

注册表中有这一项
计算机\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Keyboard Layouts\00000409
LayoutFile 为 KBDUS.DLL

但是在
[https://www.autohotkey.com/boards/viewtopic.php?f=76&t=54874&p=236131&hilit=Change+keyboard#p236131](https://www.autohotkey.com/boards/viewtopic.php?f=76&t=54874&p=236131&hilit=Change+keyboard#p236131)
这边找到的确实是你定义的 0x4090409

我通过python 安装了win32包
pip install pywin32
下面代码在我的windows可以正常切换为英文输入法
```python
import win32api
import win32gui

if __name__ == '__main__':
    hwnd = win32gui.GetForegroundWindow()
    win32api.PostMessage(hwnd, 0x0050, 0, 0x00000409)
```
  
没有搞懂为什么有两种不同的键盘布局id
由于我这边没有c#的环境也没有研究keepass的插件写法
还希望再查看一下，同时非常感谢你的开源插件。

补充一点 委托同事已经编译出插件文件 但是还是有些问题
虽然大概看到  AutoType.FilterCompilePre += OnAutoType; 这里已经有实现
但有时插件没有正确切换（猜想问题出在 1.未输入kp密码，输入密码这里就切了us键盘，在web再调用可能输出中文；2.不用输入时，web上手动切换输入法，在web再调用kp亦可能出错）

**Comment by NightDream2016** [comment]
您好，感謝您的回饋。
我自己在Windows 10 19043.1165上測試，設定系統語系為英文(美國)，
使用[GetSystemKeyboardLayoutList](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutlist)，拿出來的ID確實是0x04090409。

不過我的作法其實是參考[這個Gist](https://gist.github.com/vurdalakov/9cea795e82109fdacb7062dcb122b42e)，我後來在想這個ID可能是包含語系和鍵盤的ID，否則他不會有一個&0xFFFF跟>>16的流程，應該是為了將前兩個Byte與後兩個Byte的資訊分開處理，所以可能你查到的0x00000409是只有Keyboard的資訊。而0x04090409是包含語系(高位的兩個Byte)跟鍵盤(低位的兩個Byte)的資訊，這樣。

所以我在想也許打給PostMessage的時候只要打Keyboard的ID就好，才能確實的指定是英文鍵盤。
原本的實作用的是Language ID而不是Keyboard ID，其實也不是打0x04090409給PostWindow，如果系統是使用「其他語言的英文鍵盤」，那也許就會出錯，我目前推測是這原因，已在v1.2.0修復此問題。

另外也考量有可能是我指定預設English Keyboard的方式不對，目前一律採取先GetSystemKeyboardLayoutList然後再找有沒有英文鍵盤的做法，如果沒有就只會拿第一個語言而不是強制英文，這樣應該可以降低錯誤的機率，還請您有空再嘗試一下此版本是否可運作。
(如果不行的話也許我將來有空做一個Debug的Plgx，看能不能取得您系統的GetSystemKeyboardLayout資訊供參考，或許那樣會更有效一些。)

**Comment by anonymou3** [comment]
首先感谢你的回复和修复

暂时初步用下来都正确切到英文了
我会继续使用，看看有没有其他的问题

同时我修改了一下我的全局keepass触发热键，一开始为Shift+Alt+A  我发现Shift+Alt单独按了一下会切换输入法，这个可能也是一个问题，毕竟如果我用三个键作为热键的话 可能会先按到了Shift+Alt

对了，想到一个
我同时有一台老式的电脑安装的windows7，虽然现在倒是不怎么使用那台电脑了
记得在上面使用提示了插件兼容性有问题，插件直接一开始就运行不起来了，只能跳过这个插件的加载，我的keepass是同步到各个电脑都使用的，版本什么的是最新的
如果可能的话可以考虑兼容一下

再次感谢你的辛勤工作

**Comment by NightDream2016** [comment]
感謝回應，這裡就先將問題Close，針對Windows 7的支援我再另外開Issue。

**Comment by NightDream2016** [comment]
> 首先感谢你的回复和修复
> 
> 暂时初步用下来都正确切到英文了
> 我会继续使用，看看有没有其他的问题
> 
> 同时我修改了一下我的全局keepass触发热键，一开始为Shift+Alt+A 我发现Shift+Alt单独按了一下会切换输入法，这个可能也是一个问题，毕竟如果我用三个键作为热键的话 可能会先按到了Shift+Alt
> 
> 对了，想到一个
> 我同时有一台老式的电脑安装的windows7，虽然现在倒是不怎么使用那台电脑了
> 记得在上面使用提示了插件兼容性有问题，插件直接一开始就运行不起来了，只能跳过这个插件的加载，我的keepass是同步到各个电脑都使用的，版本什么的是最新的
> 如果可能的话可以考虑兼容一下
> 
> 再次感谢你的辛勤工作

@anonymou3 
您好。
有關Windows 7的支援版本已經上線 
[v1.2.8-beta](https://github.com/NightDream2016/AutoTypeInputLanguage/releases/tag/v1.2.8-beta)

還請您有需要的話可協助進行試用。
因為實作部分有一點改變，目前初步在我這裡的Windows 10上測試OK，之後使用會繼續觀察。
再次感謝您的回饋。
